data:
  processed: 'data/processed'

data_split:
  valid_size: 0.2

train:
  arch: 18
  batch_size: 9
  epochs: 10
  models_path: 'models'
  # scripts\notebooks should save concatenating {arch} at the end (pytorch adds .pth)

reports:
  confusion_matrix: 'reports\confusion_matrix'
  # scripts\notebooks should save concatenating {arch}.png at the end
