name: train-models
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        #with:
        #   python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |                    
          # Install our package
          python setup.py install
          
          # Call Command Line Interface
          for arch in 18 34; do           
            train --arch $arch
            done
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |                
          echo "## Data viz" >> report.md
          for arch in 18 34; do
            echo "### ResNet$arch" >> report.md
            cml-publish confusion_matrix_ResNet$arch.png --md >> report.md
          done          
          cml send-comment report.md
